root = "."
tmp_dir = "tmp"

[build]
  entrypoint = "main.go"
  cmd = "go build -o ./tmp/main ./main.go"
  bin = "./tmp/main"
  full_bin = "./tmp/main server -e dev"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "test", "packages"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  delay = 1000
  stop_on_error = false

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true