// 事件常量（与后端 signal/events.go 一致）
export const EVENTS = {
	ROOM_CREATE: "room:create",
	ROOM_JOIN: "room:join",
	ROOM_LEAVE: "room:leave",
	ROOM_LIST: "room:list",
	ROOM_CREATED: "room:created",
	ROOM_LEFT: "room:left",
	ROOM_UPDATED: "room:updated",
	MEMBER_JOINED: "member:joined",
	MEMBER_LEFT: "member:left",
	ROOM_LIST_RESULT: "room:list:result",
	ROOM_JOIN_SFU: "room:join:sfu",
	MEMBER_MIC_STATE: "member:mic-state",
	MEMBER_UPDATED: "member:updated",
	ROOM_KICK: "room:kick",
	ROOM_KICKED: "room:kicked",
	USER_MUTED: "user:muted",
	USER_UNMUTED: "user:unmuted",
	// 发言检测（无 SFU 原生 active speaker 的 provider：SRS / Cloudflare）
	MEMBER_SPEAKING: "member:speaking",
	ROOM_ACTIVE_SPEAKERS: "room:active-speakers",
	SFU_GET_ROUTER_CAPABILITIES: "sfu:get-router-capabilities",
	SFU_CREATE_TRANSPORT: "sfu:create-transport",
	SFU_CONNECT_TRANSPORT: "sfu:connect-transport",
	SFU_PRODUCE: "sfu:produce",
	SFU_CONSUME: "sfu:consume",
	SFU_PRODUCER_READY: "sfu:producer-ready",
	SFU_PRODUCER_CLOSED: "sfu:producer-closed",
	// SFU 热切换：强制断连并刷新
	SFU_PROVIDER_CHANGED: "sfu:provider-changed",
	MESSAGE_SEND: "message:send",
	MESSAGE_NEW: "message:new",
} as const;
