/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as appRouteRouteImport } from './pages/(app)/route'
import { Route as LoginIndexRouteImport } from './pages/login/index'
import { Route as appIndexRouteRouteImport } from './pages/(app)/index/route'
import { Route as appIndexIndexRouteImport } from './pages/(app)/index/index'
import { Route as appLinkIndexRouteImport } from './pages/(app)/link/index'
import { Route as appChannelIndexRouteImport } from './pages/(app)/channel/index'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRouteRoute = appIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => appRouteRoute,
} as any)
const appIndexIndexRoute = appIndexIndexRouteImport.update({
  id: '/index/',
  path: '/index/',
  getParentRoute: () => appRouteRoute,
} as any)
const appLinkIndexRoute = appLinkIndexRouteImport.update({
  id: '/link/',
  path: '/link/',
  getParentRoute: () => appRouteRoute,
} as any)
const appChannelIndexRoute = appChannelIndexRouteImport.update({
  id: '/channel/',
  path: '/channel/',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRouteRoute
  '/login/': typeof LoginIndexRoute
  '/channel/': typeof appChannelIndexRoute
  '/index/': typeof appIndexIndexRoute
  '/link/': typeof appLinkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof appIndexRouteRoute
  '/login': typeof LoginIndexRoute
  '/channel': typeof appChannelIndexRoute
  '/index': typeof appIndexIndexRoute
  '/link': typeof appLinkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/': typeof appIndexRouteRoute
  '/login/': typeof LoginIndexRoute
  '/(app)/channel/': typeof appChannelIndexRoute
  '/(app)/index/': typeof appIndexIndexRoute
  '/(app)/link/': typeof appLinkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login/' | '/channel/' | '/index/' | '/link/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/channel' | '/index' | '/link'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/'
    | '/login/'
    | '/(app)/channel/'
    | '/(app)/index/'
    | '/(app)/link/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/index/': {
      id: '/(app)/index/'
      path: '/index'
      fullPath: '/index/'
      preLoaderRoute: typeof appIndexIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/link/': {
      id: '/(app)/link/'
      path: '/link'
      fullPath: '/link/'
      preLoaderRoute: typeof appLinkIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/channel/': {
      id: '/(app)/channel/'
      path: '/channel'
      fullPath: '/channel/'
      preLoaderRoute: typeof appChannelIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appIndexRouteRoute: typeof appIndexRouteRoute
  appChannelIndexRoute: typeof appChannelIndexRoute
  appIndexIndexRoute: typeof appIndexIndexRoute
  appLinkIndexRoute: typeof appLinkIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRouteRoute: appIndexRouteRoute,
  appChannelIndexRoute: appChannelIndexRoute,
  appIndexIndexRoute: appIndexIndexRoute,
  appLinkIndexRoute: appLinkIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
