/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as appIndexRouteRouteImport } from './pages/(app)/index/route'
import { Route as appLinkIndexRouteImport } from './pages/(app)/link/index'
import { Route as appIndexIndexRouteImport } from './pages/(app)/index/index'
import { Route as appRoomRoomIdRouteImport } from './pages/(app)/room/$roomId'

const appIndexRouteRoute = appIndexRouteRouteImport.update({
  id: '/(app)/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const appLinkIndexRoute = appLinkIndexRouteImport.update({
  id: '/link/',
  path: '/link/',
  getParentRoute: () => appRouteRoute,
} as any)
const appIndexIndexRoute = appIndexIndexRouteImport.update({
  id: '/(app)/index/',
  path: '/index/',
  getParentRoute: () => rootRouteImport,
} as any)
const appRoomRoomIdRoute = appRoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/room/$roomId': typeof appRoomRoomIdRoute
  '/index': typeof appIndexIndexRoute
  '/link': typeof appLinkIndexRoute
}
export interface FileRoutesByTo {
  '/room/$roomId': typeof appRoomRoomIdRoute
  '/index': typeof appIndexIndexRoute
  '/link': typeof appLinkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/': typeof appIndexRouteRoute
  '/(app)/room/$roomId': typeof appRoomRoomIdRoute
  '/(app)/index/': typeof appIndexIndexRoute
  '/(app)/link/': typeof appLinkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/room/$roomId' | '/index' | '/link'
  fileRoutesByTo: FileRoutesByTo
  to: '/room/$roomId' | '/index' | '/link'
  id:
    | '__root__'
    | '/(app)/'
    | '/(app)/room/$roomId'
    | '/(app)/index/'
    | '/(app)/link/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appIndexRouteRoute: typeof appIndexRouteRoute
  appIndexIndexRoute: typeof appIndexIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/(app)/': {
      id: '/(app)/'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/link/': {
      id: '/(app)/link/'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof appLinkIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/index/': {
      id: '/(app)/index/'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof appIndexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/room/$roomId': {
      id: '/(app)/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof appRoomRoomIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  appIndexRouteRoute: appIndexRouteRoute,
  appIndexIndexRoute: appIndexIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
