/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as appIndexRouteRouteImport } from './pages/(app)/index/route'
import { Route as appLinkIndexRouteImport } from './pages/(app)/link/index'
import { Route as appRoomRoomIdRouteImport } from './pages/(app)/room/$roomId'

const appIndexRouteRoute = appIndexRouteRouteImport.update({
  id: '/(app)/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const appLinkIndexRoute = appLinkIndexRouteImport.update({
  id: '/(app)/link/',
  path: '/link/',
  getParentRoute: () => rootRouteImport,
} as any)
const appRoomRoomIdRoute = appRoomRoomIdRouteImport.update({
  id: '/(app)/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRouteRoute
  '/room/$roomId': typeof appRoomRoomIdRoute
  '/link/': typeof appLinkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof appIndexRouteRoute
  '/room/$roomId': typeof appRoomRoomIdRoute
  '/link': typeof appLinkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/': typeof appIndexRouteRoute
  '/(app)/room/$roomId': typeof appRoomRoomIdRoute
  '/(app)/link/': typeof appLinkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/room/$roomId' | '/link/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/room/$roomId' | '/link'
  id: '__root__' | '/(app)/' | '/(app)/room/$roomId' | '/(app)/link/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appIndexRouteRoute: typeof appIndexRouteRoute
  appRoomRoomIdRoute: typeof appRoomRoomIdRoute
  appLinkIndexRoute: typeof appLinkIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/(app)/': {
      id: '/(app)/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/link/': {
      id: '/(app)/link/'
      path: '/link'
      fullPath: '/link/'
      preLoaderRoute: typeof appLinkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/room/$roomId': {
      id: '/(app)/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof appRoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  appIndexRouteRoute: appIndexRouteRoute,
  appRoomRoomIdRoute: appRoomRoomIdRoute,
  appLinkIndexRoute: appLinkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
