root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main server -e dev"
  full_bin = "./tmp/main server -e dev"
  include_ext = ["go"]
  exclude_dir = ["tmp", "build", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test\\.go$"]
  exclude_unchanged = true
  follow_symlink = false
  log = "build-errors.log"
  delay = 500
  stop_on_error = true
  send_interrupt = true
  kill_delay = 500

[log]
  time = false
  main_only = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
