/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as appRouteRouteImport } from './pages/(app)/route'
import { Route as LoginIndexRouteImport } from './pages/login/index'
import { Route as appProfileRouteRouteImport } from './pages/(app)/profile/route'
import { Route as appManageRouteRouteImport } from './pages/(app)/manage/route'
import { Route as appIndexRouteRouteImport } from './pages/(app)/index/route'
import { Route as appIndexIndexRouteImport } from './pages/(app)/index/index'
import { Route as appManageIndexRouteImport } from './pages/(app)/manage/index'
import { Route as appLinkIndexRouteImport } from './pages/(app)/link/index'
import { Route as appDiscoverIndexRouteImport } from './pages/(app)/discover/index'
import { Route as appChatIndexRouteImport } from './pages/(app)/chat/index'
import { Route as appManageUsersIndexRouteImport } from './pages/(app)/manage/users/index'
import { Route as appManageStorageIndexRouteImport } from './pages/(app)/manage/storage/index'
import { Route as appManageSfuIndexRouteImport } from './pages/(app)/manage/sfu/index'
import { Route as appManageOauthIndexRouteImport } from './pages/(app)/manage/oauth/index'
import { Route as appManageMuteIndexRouteImport } from './pages/(app)/manage/mute/index'
import { Route as appManageMonitorIndexRouteImport } from './pages/(app)/manage/monitor/index'
import { Route as appManageEmailIndexRouteImport } from './pages/(app)/manage/email/index'
import { Route as appManageDomainsIndexRouteImport } from './pages/(app)/manage/domains/index'
import { Route as appManageClusterIndexRouteImport } from './pages/(app)/manage/cluster/index'
import { Route as appManageBotPluginsIndexRouteImport } from './pages/(app)/manage/bot-plugins/index'
import { Route as appManageBanIndexRouteImport } from './pages/(app)/manage/ban/index'
import { Route as appManageApikeyIndexRouteImport } from './pages/(app)/manage/apikey/index'
import { Route as appDomainDomainUUIDIndexRouteImport } from './pages/(app)/domain/$domainUUID/index'
import { Route as appManageDomainsDomainUUIDIndexRouteImport } from './pages/(app)/manage/domains/$domainUUID/index'
import { Route as appInviteDCodeIndexRouteImport } from './pages/(app)/invite/d/$code/index'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const appProfileRouteRoute = appProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appRouteRoute,
} as any)
const appManageRouteRoute = appManageRouteRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => appRouteRoute,
} as any)
const appIndexRouteRoute = appIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => appRouteRoute,
} as any)
const appIndexIndexRoute = appIndexIndexRouteImport.update({
  id: '/index/',
  path: '/index/',
  getParentRoute: () => appRouteRoute,
} as any)
const appManageIndexRoute = appManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appLinkIndexRoute = appLinkIndexRouteImport.update({
  id: '/link/',
  path: '/link/',
  getParentRoute: () => appRouteRoute,
} as any)
const appDiscoverIndexRoute = appDiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => appRouteRoute,
} as any)
const appChatIndexRoute = appChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => appRouteRoute,
} as any)
const appManageUsersIndexRoute = appManageUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appManageStorageIndexRoute = appManageStorageIndexRouteImport.update({
  id: '/storage/',
  path: '/storage/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appManageSfuIndexRoute = appManageSfuIndexRouteImport.update({
  id: '/sfu/',
  path: '/sfu/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appManageOauthIndexRoute = appManageOauthIndexRouteImport.update({
  id: '/oauth/',
  path: '/oauth/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appManageMuteIndexRoute = appManageMuteIndexRouteImport.update({
  id: '/mute/',
  path: '/mute/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appManageMonitorIndexRoute = appManageMonitorIndexRouteImport.update({
  id: '/monitor/',
  path: '/monitor/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appManageEmailIndexRoute = appManageEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appManageDomainsIndexRoute = appManageDomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appManageClusterIndexRoute = appManageClusterIndexRouteImport.update({
  id: '/cluster/',
  path: '/cluster/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appManageBotPluginsIndexRoute =
  appManageBotPluginsIndexRouteImport.update({
    id: '/bot-plugins/',
    path: '/bot-plugins/',
    getParentRoute: () => appManageRouteRoute,
  } as any)
const appManageBanIndexRoute = appManageBanIndexRouteImport.update({
  id: '/ban/',
  path: '/ban/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appManageApikeyIndexRoute = appManageApikeyIndexRouteImport.update({
  id: '/apikey/',
  path: '/apikey/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appDomainDomainUUIDIndexRoute =
  appDomainDomainUUIDIndexRouteImport.update({
    id: '/domain/$domainUUID/',
    path: '/domain/$domainUUID/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appManageDomainsDomainUUIDIndexRoute =
  appManageDomainsDomainUUIDIndexRouteImport.update({
    id: '/domains/$domainUUID/',
    path: '/domains/$domainUUID/',
    getParentRoute: () => appManageRouteRoute,
  } as any)
const appInviteDCodeIndexRoute = appInviteDCodeIndexRouteImport.update({
  id: '/invite/d/$code/',
  path: '/invite/d/$code/',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRouteRoute
  '/manage': typeof appManageRouteRouteWithChildren
  '/profile': typeof appProfileRouteRoute
  '/login/': typeof LoginIndexRoute
  '/chat/': typeof appChatIndexRoute
  '/discover/': typeof appDiscoverIndexRoute
  '/index/': typeof appIndexIndexRoute
  '/link/': typeof appLinkIndexRoute
  '/manage/': typeof appManageIndexRoute
  '/domain/$domainUUID/': typeof appDomainDomainUUIDIndexRoute
  '/manage/apikey/': typeof appManageApikeyIndexRoute
  '/manage/ban/': typeof appManageBanIndexRoute
  '/manage/bot-plugins/': typeof appManageBotPluginsIndexRoute
  '/manage/cluster/': typeof appManageClusterIndexRoute
  '/manage/domains/': typeof appManageDomainsIndexRoute
  '/manage/email/': typeof appManageEmailIndexRoute
  '/manage/monitor/': typeof appManageMonitorIndexRoute
  '/manage/mute/': typeof appManageMuteIndexRoute
  '/manage/oauth/': typeof appManageOauthIndexRoute
  '/manage/sfu/': typeof appManageSfuIndexRoute
  '/manage/storage/': typeof appManageStorageIndexRoute
  '/manage/users/': typeof appManageUsersIndexRoute
  '/invite/d/$code/': typeof appInviteDCodeIndexRoute
  '/manage/domains/$domainUUID/': typeof appManageDomainsDomainUUIDIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof appIndexRouteRoute
  '/profile': typeof appProfileRouteRoute
  '/login': typeof LoginIndexRoute
  '/chat': typeof appChatIndexRoute
  '/discover': typeof appDiscoverIndexRoute
  '/index': typeof appIndexIndexRoute
  '/link': typeof appLinkIndexRoute
  '/manage': typeof appManageIndexRoute
  '/domain/$domainUUID': typeof appDomainDomainUUIDIndexRoute
  '/manage/apikey': typeof appManageApikeyIndexRoute
  '/manage/ban': typeof appManageBanIndexRoute
  '/manage/bot-plugins': typeof appManageBotPluginsIndexRoute
  '/manage/cluster': typeof appManageClusterIndexRoute
  '/manage/domains': typeof appManageDomainsIndexRoute
  '/manage/email': typeof appManageEmailIndexRoute
  '/manage/monitor': typeof appManageMonitorIndexRoute
  '/manage/mute': typeof appManageMuteIndexRoute
  '/manage/oauth': typeof appManageOauthIndexRoute
  '/manage/sfu': typeof appManageSfuIndexRoute
  '/manage/storage': typeof appManageStorageIndexRoute
  '/manage/users': typeof appManageUsersIndexRoute
  '/invite/d/$code': typeof appInviteDCodeIndexRoute
  '/manage/domains/$domainUUID': typeof appManageDomainsDomainUUIDIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/': typeof appIndexRouteRoute
  '/(app)/manage': typeof appManageRouteRouteWithChildren
  '/(app)/profile': typeof appProfileRouteRoute
  '/login/': typeof LoginIndexRoute
  '/(app)/chat/': typeof appChatIndexRoute
  '/(app)/discover/': typeof appDiscoverIndexRoute
  '/(app)/index/': typeof appIndexIndexRoute
  '/(app)/link/': typeof appLinkIndexRoute
  '/(app)/manage/': typeof appManageIndexRoute
  '/(app)/domain/$domainUUID/': typeof appDomainDomainUUIDIndexRoute
  '/(app)/manage/apikey/': typeof appManageApikeyIndexRoute
  '/(app)/manage/ban/': typeof appManageBanIndexRoute
  '/(app)/manage/bot-plugins/': typeof appManageBotPluginsIndexRoute
  '/(app)/manage/cluster/': typeof appManageClusterIndexRoute
  '/(app)/manage/domains/': typeof appManageDomainsIndexRoute
  '/(app)/manage/email/': typeof appManageEmailIndexRoute
  '/(app)/manage/monitor/': typeof appManageMonitorIndexRoute
  '/(app)/manage/mute/': typeof appManageMuteIndexRoute
  '/(app)/manage/oauth/': typeof appManageOauthIndexRoute
  '/(app)/manage/sfu/': typeof appManageSfuIndexRoute
  '/(app)/manage/storage/': typeof appManageStorageIndexRoute
  '/(app)/manage/users/': typeof appManageUsersIndexRoute
  '/(app)/invite/d/$code/': typeof appInviteDCodeIndexRoute
  '/(app)/manage/domains/$domainUUID/': typeof appManageDomainsDomainUUIDIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manage'
    | '/profile'
    | '/login/'
    | '/chat/'
    | '/discover/'
    | '/index/'
    | '/link/'
    | '/manage/'
    | '/domain/$domainUUID/'
    | '/manage/apikey/'
    | '/manage/ban/'
    | '/manage/bot-plugins/'
    | '/manage/cluster/'
    | '/manage/domains/'
    | '/manage/email/'
    | '/manage/monitor/'
    | '/manage/mute/'
    | '/manage/oauth/'
    | '/manage/sfu/'
    | '/manage/storage/'
    | '/manage/users/'
    | '/invite/d/$code/'
    | '/manage/domains/$domainUUID/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/login'
    | '/chat'
    | '/discover'
    | '/index'
    | '/link'
    | '/manage'
    | '/domain/$domainUUID'
    | '/manage/apikey'
    | '/manage/ban'
    | '/manage/bot-plugins'
    | '/manage/cluster'
    | '/manage/domains'
    | '/manage/email'
    | '/manage/monitor'
    | '/manage/mute'
    | '/manage/oauth'
    | '/manage/sfu'
    | '/manage/storage'
    | '/manage/users'
    | '/invite/d/$code'
    | '/manage/domains/$domainUUID'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/'
    | '/(app)/manage'
    | '/(app)/profile'
    | '/login/'
    | '/(app)/chat/'
    | '/(app)/discover/'
    | '/(app)/index/'
    | '/(app)/link/'
    | '/(app)/manage/'
    | '/(app)/domain/$domainUUID/'
    | '/(app)/manage/apikey/'
    | '/(app)/manage/ban/'
    | '/(app)/manage/bot-plugins/'
    | '/(app)/manage/cluster/'
    | '/(app)/manage/domains/'
    | '/(app)/manage/email/'
    | '/(app)/manage/monitor/'
    | '/(app)/manage/mute/'
    | '/(app)/manage/oauth/'
    | '/(app)/manage/sfu/'
    | '/(app)/manage/storage/'
    | '/(app)/manage/users/'
    | '/(app)/invite/d/$code/'
    | '/(app)/manage/domains/$domainUUID/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/manage': {
      id: '/(app)/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof appManageRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/': {
      id: '/(app)/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/index/': {
      id: '/(app)/index/'
      path: '/index'
      fullPath: '/index/'
      preLoaderRoute: typeof appIndexIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/manage/': {
      id: '/(app)/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof appManageIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/link/': {
      id: '/(app)/link/'
      path: '/link'
      fullPath: '/link/'
      preLoaderRoute: typeof appLinkIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/discover/': {
      id: '/(app)/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof appDiscoverIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/chat/': {
      id: '/(app)/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof appChatIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/manage/users/': {
      id: '/(app)/manage/users/'
      path: '/users'
      fullPath: '/manage/users/'
      preLoaderRoute: typeof appManageUsersIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/storage/': {
      id: '/(app)/manage/storage/'
      path: '/storage'
      fullPath: '/manage/storage/'
      preLoaderRoute: typeof appManageStorageIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/sfu/': {
      id: '/(app)/manage/sfu/'
      path: '/sfu'
      fullPath: '/manage/sfu/'
      preLoaderRoute: typeof appManageSfuIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/oauth/': {
      id: '/(app)/manage/oauth/'
      path: '/oauth'
      fullPath: '/manage/oauth/'
      preLoaderRoute: typeof appManageOauthIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/mute/': {
      id: '/(app)/manage/mute/'
      path: '/mute'
      fullPath: '/manage/mute/'
      preLoaderRoute: typeof appManageMuteIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/monitor/': {
      id: '/(app)/manage/monitor/'
      path: '/monitor'
      fullPath: '/manage/monitor/'
      preLoaderRoute: typeof appManageMonitorIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/email/': {
      id: '/(app)/manage/email/'
      path: '/email'
      fullPath: '/manage/email/'
      preLoaderRoute: typeof appManageEmailIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/domains/': {
      id: '/(app)/manage/domains/'
      path: '/domains'
      fullPath: '/manage/domains/'
      preLoaderRoute: typeof appManageDomainsIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/cluster/': {
      id: '/(app)/manage/cluster/'
      path: '/cluster'
      fullPath: '/manage/cluster/'
      preLoaderRoute: typeof appManageClusterIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/bot-plugins/': {
      id: '/(app)/manage/bot-plugins/'
      path: '/bot-plugins'
      fullPath: '/manage/bot-plugins/'
      preLoaderRoute: typeof appManageBotPluginsIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/ban/': {
      id: '/(app)/manage/ban/'
      path: '/ban'
      fullPath: '/manage/ban/'
      preLoaderRoute: typeof appManageBanIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/apikey/': {
      id: '/(app)/manage/apikey/'
      path: '/apikey'
      fullPath: '/manage/apikey/'
      preLoaderRoute: typeof appManageApikeyIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/domain/$domainUUID/': {
      id: '/(app)/domain/$domainUUID/'
      path: '/domain/$domainUUID'
      fullPath: '/domain/$domainUUID/'
      preLoaderRoute: typeof appDomainDomainUUIDIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/manage/domains/$domainUUID/': {
      id: '/(app)/manage/domains/$domainUUID/'
      path: '/domains/$domainUUID'
      fullPath: '/manage/domains/$domainUUID/'
      preLoaderRoute: typeof appManageDomainsDomainUUIDIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/invite/d/$code/': {
      id: '/(app)/invite/d/$code/'
      path: '/invite/d/$code'
      fullPath: '/invite/d/$code/'
      preLoaderRoute: typeof appInviteDCodeIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appManageRouteRouteChildren {
  appManageIndexRoute: typeof appManageIndexRoute
  appManageApikeyIndexRoute: typeof appManageApikeyIndexRoute
  appManageBanIndexRoute: typeof appManageBanIndexRoute
  appManageBotPluginsIndexRoute: typeof appManageBotPluginsIndexRoute
  appManageClusterIndexRoute: typeof appManageClusterIndexRoute
  appManageDomainsIndexRoute: typeof appManageDomainsIndexRoute
  appManageEmailIndexRoute: typeof appManageEmailIndexRoute
  appManageMonitorIndexRoute: typeof appManageMonitorIndexRoute
  appManageMuteIndexRoute: typeof appManageMuteIndexRoute
  appManageOauthIndexRoute: typeof appManageOauthIndexRoute
  appManageSfuIndexRoute: typeof appManageSfuIndexRoute
  appManageStorageIndexRoute: typeof appManageStorageIndexRoute
  appManageUsersIndexRoute: typeof appManageUsersIndexRoute
  appManageDomainsDomainUUIDIndexRoute: typeof appManageDomainsDomainUUIDIndexRoute
}

const appManageRouteRouteChildren: appManageRouteRouteChildren = {
  appManageIndexRoute: appManageIndexRoute,
  appManageApikeyIndexRoute: appManageApikeyIndexRoute,
  appManageBanIndexRoute: appManageBanIndexRoute,
  appManageBotPluginsIndexRoute: appManageBotPluginsIndexRoute,
  appManageClusterIndexRoute: appManageClusterIndexRoute,
  appManageDomainsIndexRoute: appManageDomainsIndexRoute,
  appManageEmailIndexRoute: appManageEmailIndexRoute,
  appManageMonitorIndexRoute: appManageMonitorIndexRoute,
  appManageMuteIndexRoute: appManageMuteIndexRoute,
  appManageOauthIndexRoute: appManageOauthIndexRoute,
  appManageSfuIndexRoute: appManageSfuIndexRoute,
  appManageStorageIndexRoute: appManageStorageIndexRoute,
  appManageUsersIndexRoute: appManageUsersIndexRoute,
  appManageDomainsDomainUUIDIndexRoute: appManageDomainsDomainUUIDIndexRoute,
}

const appManageRouteRouteWithChildren = appManageRouteRoute._addFileChildren(
  appManageRouteRouteChildren,
)

interface appRouteRouteChildren {
  appIndexRouteRoute: typeof appIndexRouteRoute
  appManageRouteRoute: typeof appManageRouteRouteWithChildren
  appProfileRouteRoute: typeof appProfileRouteRoute
  appChatIndexRoute: typeof appChatIndexRoute
  appDiscoverIndexRoute: typeof appDiscoverIndexRoute
  appIndexIndexRoute: typeof appIndexIndexRoute
  appLinkIndexRoute: typeof appLinkIndexRoute
  appDomainDomainUUIDIndexRoute: typeof appDomainDomainUUIDIndexRoute
  appInviteDCodeIndexRoute: typeof appInviteDCodeIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRouteRoute: appIndexRouteRoute,
  appManageRouteRoute: appManageRouteRouteWithChildren,
  appProfileRouteRoute: appProfileRouteRoute,
  appChatIndexRoute: appChatIndexRoute,
  appDiscoverIndexRoute: appDiscoverIndexRoute,
  appIndexIndexRoute: appIndexIndexRoute,
  appLinkIndexRoute: appLinkIndexRoute,
  appDomainDomainUUIDIndexRoute: appDomainDomainUUIDIndexRoute,
  appInviteDCodeIndexRoute: appInviteDCodeIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
