/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as appRouteRouteImport } from './pages/(app)/route'
import { Route as LoginIndexRouteImport } from './pages/login/index'
import { Route as appProfileRouteRouteImport } from './pages/(app)/profile/route'
import { Route as appManageRouteRouteImport } from './pages/(app)/manage/route'
import { Route as appIndexRouteRouteImport } from './pages/(app)/index/route'
import { Route as appIndexIndexRouteImport } from './pages/(app)/index/index'
import { Route as appManageIndexRouteImport } from './pages/(app)/manage/index'
import { Route as appLinkIndexRouteImport } from './pages/(app)/link/index'
import { Route as appDiscoverIndexRouteImport } from './pages/(app)/discover/index'
import { Route as appChatIndexRouteImport } from './pages/(app)/chat/index'
import { Route as appChannelIndexRouteImport } from './pages/(app)/channel/index'
import { Route as appManageUsersIndexRouteImport } from './pages/(app)/manage/users/index'
import { Route as appManageStorageIndexRouteImport } from './pages/(app)/manage/storage/index'
import { Route as appManageSfuIndexRouteImport } from './pages/(app)/manage/sfu/index'
import { Route as appManagePermissionIndexRouteImport } from './pages/(app)/manage/permission/index'
import { Route as appManageOauthIndexRouteImport } from './pages/(app)/manage/oauth/index'
import { Route as appManageMuteIndexRouteImport } from './pages/(app)/manage/mute/index'
import { Route as appManageMonitorIndexRouteImport } from './pages/(app)/manage/monitor/index'
import { Route as appManageEmailIndexRouteImport } from './pages/(app)/manage/email/index'
import { Route as appManageBotPluginsIndexRouteImport } from './pages/(app)/manage/bot-plugins/index'
import { Route as appManageBanIndexRouteImport } from './pages/(app)/manage/ban/index'
import { Route as appManageApikeyIndexRouteImport } from './pages/(app)/manage/apikey/index'
import { Route as appGuildGuildUUIDIndexRouteImport } from './pages/(app)/guild/$guildUUID/index'
import { Route as appGuildGuildUUIDManageRouteImport } from './pages/(app)/guild/$guildUUID/manage'
import { Route as appInviteGCodeIndexRouteImport } from './pages/(app)/invite/g/$code/index'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const appProfileRouteRoute = appProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appRouteRoute,
} as any)
const appManageRouteRoute = appManageRouteRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => appRouteRoute,
} as any)
const appIndexRouteRoute = appIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => appRouteRoute,
} as any)
const appIndexIndexRoute = appIndexIndexRouteImport.update({
  id: '/index/',
  path: '/index/',
  getParentRoute: () => appRouteRoute,
} as any)
const appManageIndexRoute = appManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appLinkIndexRoute = appLinkIndexRouteImport.update({
  id: '/link/',
  path: '/link/',
  getParentRoute: () => appRouteRoute,
} as any)
const appDiscoverIndexRoute = appDiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => appRouteRoute,
} as any)
const appChatIndexRoute = appChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => appRouteRoute,
} as any)
const appChannelIndexRoute = appChannelIndexRouteImport.update({
  id: '/channel/',
  path: '/channel/',
  getParentRoute: () => appRouteRoute,
} as any)
const appManageUsersIndexRoute = appManageUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appManageStorageIndexRoute = appManageStorageIndexRouteImport.update({
  id: '/storage/',
  path: '/storage/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appManageSfuIndexRoute = appManageSfuIndexRouteImport.update({
  id: '/sfu/',
  path: '/sfu/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appManagePermissionIndexRoute =
  appManagePermissionIndexRouteImport.update({
    id: '/permission/',
    path: '/permission/',
    getParentRoute: () => appManageRouteRoute,
  } as any)
const appManageOauthIndexRoute = appManageOauthIndexRouteImport.update({
  id: '/oauth/',
  path: '/oauth/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appManageMuteIndexRoute = appManageMuteIndexRouteImport.update({
  id: '/mute/',
  path: '/mute/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appManageMonitorIndexRoute = appManageMonitorIndexRouteImport.update({
  id: '/monitor/',
  path: '/monitor/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appManageEmailIndexRoute = appManageEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appManageBotPluginsIndexRoute =
  appManageBotPluginsIndexRouteImport.update({
    id: '/bot-plugins/',
    path: '/bot-plugins/',
    getParentRoute: () => appManageRouteRoute,
  } as any)
const appManageBanIndexRoute = appManageBanIndexRouteImport.update({
  id: '/ban/',
  path: '/ban/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appManageApikeyIndexRoute = appManageApikeyIndexRouteImport.update({
  id: '/apikey/',
  path: '/apikey/',
  getParentRoute: () => appManageRouteRoute,
} as any)
const appGuildGuildUUIDIndexRoute = appGuildGuildUUIDIndexRouteImport.update({
  id: '/guild/$guildUUID/',
  path: '/guild/$guildUUID/',
  getParentRoute: () => appRouteRoute,
} as any)
const appGuildGuildUUIDManageRoute = appGuildGuildUUIDManageRouteImport.update({
  id: '/guild/$guildUUID/manage',
  path: '/guild/$guildUUID/manage',
  getParentRoute: () => appRouteRoute,
} as any)
const appInviteGCodeIndexRoute = appInviteGCodeIndexRouteImport.update({
  id: '/invite/g/$code/',
  path: '/invite/g/$code/',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRouteRoute
  '/manage': typeof appManageRouteRouteWithChildren
  '/profile': typeof appProfileRouteRoute
  '/login/': typeof LoginIndexRoute
  '/channel/': typeof appChannelIndexRoute
  '/chat/': typeof appChatIndexRoute
  '/discover/': typeof appDiscoverIndexRoute
  '/index/': typeof appIndexIndexRoute
  '/link/': typeof appLinkIndexRoute
  '/manage/': typeof appManageIndexRoute
  '/guild/$guildUUID/manage': typeof appGuildGuildUUIDManageRoute
  '/guild/$guildUUID/': typeof appGuildGuildUUIDIndexRoute
  '/manage/apikey/': typeof appManageApikeyIndexRoute
  '/manage/ban/': typeof appManageBanIndexRoute
  '/manage/bot-plugins/': typeof appManageBotPluginsIndexRoute
  '/manage/email/': typeof appManageEmailIndexRoute
  '/manage/monitor/': typeof appManageMonitorIndexRoute
  '/manage/mute/': typeof appManageMuteIndexRoute
  '/manage/oauth/': typeof appManageOauthIndexRoute
  '/manage/permission/': typeof appManagePermissionIndexRoute
  '/manage/sfu/': typeof appManageSfuIndexRoute
  '/manage/storage/': typeof appManageStorageIndexRoute
  '/manage/users/': typeof appManageUsersIndexRoute
  '/invite/g/$code/': typeof appInviteGCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof appIndexRouteRoute
  '/profile': typeof appProfileRouteRoute
  '/login': typeof LoginIndexRoute
  '/channel': typeof appChannelIndexRoute
  '/chat': typeof appChatIndexRoute
  '/discover': typeof appDiscoverIndexRoute
  '/index': typeof appIndexIndexRoute
  '/link': typeof appLinkIndexRoute
  '/manage': typeof appManageIndexRoute
  '/guild/$guildUUID/manage': typeof appGuildGuildUUIDManageRoute
  '/guild/$guildUUID': typeof appGuildGuildUUIDIndexRoute
  '/manage/apikey': typeof appManageApikeyIndexRoute
  '/manage/ban': typeof appManageBanIndexRoute
  '/manage/bot-plugins': typeof appManageBotPluginsIndexRoute
  '/manage/email': typeof appManageEmailIndexRoute
  '/manage/monitor': typeof appManageMonitorIndexRoute
  '/manage/mute': typeof appManageMuteIndexRoute
  '/manage/oauth': typeof appManageOauthIndexRoute
  '/manage/permission': typeof appManagePermissionIndexRoute
  '/manage/sfu': typeof appManageSfuIndexRoute
  '/manage/storage': typeof appManageStorageIndexRoute
  '/manage/users': typeof appManageUsersIndexRoute
  '/invite/g/$code': typeof appInviteGCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/': typeof appIndexRouteRoute
  '/(app)/manage': typeof appManageRouteRouteWithChildren
  '/(app)/profile': typeof appProfileRouteRoute
  '/login/': typeof LoginIndexRoute
  '/(app)/channel/': typeof appChannelIndexRoute
  '/(app)/chat/': typeof appChatIndexRoute
  '/(app)/discover/': typeof appDiscoverIndexRoute
  '/(app)/index/': typeof appIndexIndexRoute
  '/(app)/link/': typeof appLinkIndexRoute
  '/(app)/manage/': typeof appManageIndexRoute
  '/(app)/guild/$guildUUID/manage': typeof appGuildGuildUUIDManageRoute
  '/(app)/guild/$guildUUID/': typeof appGuildGuildUUIDIndexRoute
  '/(app)/manage/apikey/': typeof appManageApikeyIndexRoute
  '/(app)/manage/ban/': typeof appManageBanIndexRoute
  '/(app)/manage/bot-plugins/': typeof appManageBotPluginsIndexRoute
  '/(app)/manage/email/': typeof appManageEmailIndexRoute
  '/(app)/manage/monitor/': typeof appManageMonitorIndexRoute
  '/(app)/manage/mute/': typeof appManageMuteIndexRoute
  '/(app)/manage/oauth/': typeof appManageOauthIndexRoute
  '/(app)/manage/permission/': typeof appManagePermissionIndexRoute
  '/(app)/manage/sfu/': typeof appManageSfuIndexRoute
  '/(app)/manage/storage/': typeof appManageStorageIndexRoute
  '/(app)/manage/users/': typeof appManageUsersIndexRoute
  '/(app)/invite/g/$code/': typeof appInviteGCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manage'
    | '/profile'
    | '/login/'
    | '/channel/'
    | '/chat/'
    | '/discover/'
    | '/index/'
    | '/link/'
    | '/manage/'
    | '/guild/$guildUUID/manage'
    | '/guild/$guildUUID/'
    | '/manage/apikey/'
    | '/manage/ban/'
    | '/manage/bot-plugins/'
    | '/manage/email/'
    | '/manage/monitor/'
    | '/manage/mute/'
    | '/manage/oauth/'
    | '/manage/permission/'
    | '/manage/sfu/'
    | '/manage/storage/'
    | '/manage/users/'
    | '/invite/g/$code/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/login'
    | '/channel'
    | '/chat'
    | '/discover'
    | '/index'
    | '/link'
    | '/manage'
    | '/guild/$guildUUID/manage'
    | '/guild/$guildUUID'
    | '/manage/apikey'
    | '/manage/ban'
    | '/manage/bot-plugins'
    | '/manage/email'
    | '/manage/monitor'
    | '/manage/mute'
    | '/manage/oauth'
    | '/manage/permission'
    | '/manage/sfu'
    | '/manage/storage'
    | '/manage/users'
    | '/invite/g/$code'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/'
    | '/(app)/manage'
    | '/(app)/profile'
    | '/login/'
    | '/(app)/channel/'
    | '/(app)/chat/'
    | '/(app)/discover/'
    | '/(app)/index/'
    | '/(app)/link/'
    | '/(app)/manage/'
    | '/(app)/guild/$guildUUID/manage'
    | '/(app)/guild/$guildUUID/'
    | '/(app)/manage/apikey/'
    | '/(app)/manage/ban/'
    | '/(app)/manage/bot-plugins/'
    | '/(app)/manage/email/'
    | '/(app)/manage/monitor/'
    | '/(app)/manage/mute/'
    | '/(app)/manage/oauth/'
    | '/(app)/manage/permission/'
    | '/(app)/manage/sfu/'
    | '/(app)/manage/storage/'
    | '/(app)/manage/users/'
    | '/(app)/invite/g/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/manage': {
      id: '/(app)/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof appManageRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/': {
      id: '/(app)/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/index/': {
      id: '/(app)/index/'
      path: '/index'
      fullPath: '/index/'
      preLoaderRoute: typeof appIndexIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/manage/': {
      id: '/(app)/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof appManageIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/link/': {
      id: '/(app)/link/'
      path: '/link'
      fullPath: '/link/'
      preLoaderRoute: typeof appLinkIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/discover/': {
      id: '/(app)/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof appDiscoverIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/chat/': {
      id: '/(app)/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof appChatIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/channel/': {
      id: '/(app)/channel/'
      path: '/channel'
      fullPath: '/channel/'
      preLoaderRoute: typeof appChannelIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/manage/users/': {
      id: '/(app)/manage/users/'
      path: '/users'
      fullPath: '/manage/users/'
      preLoaderRoute: typeof appManageUsersIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/storage/': {
      id: '/(app)/manage/storage/'
      path: '/storage'
      fullPath: '/manage/storage/'
      preLoaderRoute: typeof appManageStorageIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/sfu/': {
      id: '/(app)/manage/sfu/'
      path: '/sfu'
      fullPath: '/manage/sfu/'
      preLoaderRoute: typeof appManageSfuIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/permission/': {
      id: '/(app)/manage/permission/'
      path: '/permission'
      fullPath: '/manage/permission/'
      preLoaderRoute: typeof appManagePermissionIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/oauth/': {
      id: '/(app)/manage/oauth/'
      path: '/oauth'
      fullPath: '/manage/oauth/'
      preLoaderRoute: typeof appManageOauthIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/mute/': {
      id: '/(app)/manage/mute/'
      path: '/mute'
      fullPath: '/manage/mute/'
      preLoaderRoute: typeof appManageMuteIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/monitor/': {
      id: '/(app)/manage/monitor/'
      path: '/monitor'
      fullPath: '/manage/monitor/'
      preLoaderRoute: typeof appManageMonitorIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/email/': {
      id: '/(app)/manage/email/'
      path: '/email'
      fullPath: '/manage/email/'
      preLoaderRoute: typeof appManageEmailIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/bot-plugins/': {
      id: '/(app)/manage/bot-plugins/'
      path: '/bot-plugins'
      fullPath: '/manage/bot-plugins/'
      preLoaderRoute: typeof appManageBotPluginsIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/ban/': {
      id: '/(app)/manage/ban/'
      path: '/ban'
      fullPath: '/manage/ban/'
      preLoaderRoute: typeof appManageBanIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/manage/apikey/': {
      id: '/(app)/manage/apikey/'
      path: '/apikey'
      fullPath: '/manage/apikey/'
      preLoaderRoute: typeof appManageApikeyIndexRouteImport
      parentRoute: typeof appManageRouteRoute
    }
    '/(app)/guild/$guildUUID/': {
      id: '/(app)/guild/$guildUUID/'
      path: '/guild/$guildUUID'
      fullPath: '/guild/$guildUUID/'
      preLoaderRoute: typeof appGuildGuildUUIDIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/guild/$guildUUID/manage': {
      id: '/(app)/guild/$guildUUID/manage'
      path: '/guild/$guildUUID/manage'
      fullPath: '/guild/$guildUUID/manage'
      preLoaderRoute: typeof appGuildGuildUUIDManageRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/invite/g/$code/': {
      id: '/(app)/invite/g/$code/'
      path: '/invite/g/$code'
      fullPath: '/invite/g/$code/'
      preLoaderRoute: typeof appInviteGCodeIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appManageRouteRouteChildren {
  appManageIndexRoute: typeof appManageIndexRoute
  appManageApikeyIndexRoute: typeof appManageApikeyIndexRoute
  appManageBanIndexRoute: typeof appManageBanIndexRoute
  appManageBotPluginsIndexRoute: typeof appManageBotPluginsIndexRoute
  appManageEmailIndexRoute: typeof appManageEmailIndexRoute
  appManageMonitorIndexRoute: typeof appManageMonitorIndexRoute
  appManageMuteIndexRoute: typeof appManageMuteIndexRoute
  appManageOauthIndexRoute: typeof appManageOauthIndexRoute
  appManagePermissionIndexRoute: typeof appManagePermissionIndexRoute
  appManageSfuIndexRoute: typeof appManageSfuIndexRoute
  appManageStorageIndexRoute: typeof appManageStorageIndexRoute
  appManageUsersIndexRoute: typeof appManageUsersIndexRoute
}

const appManageRouteRouteChildren: appManageRouteRouteChildren = {
  appManageIndexRoute: appManageIndexRoute,
  appManageApikeyIndexRoute: appManageApikeyIndexRoute,
  appManageBanIndexRoute: appManageBanIndexRoute,
  appManageBotPluginsIndexRoute: appManageBotPluginsIndexRoute,
  appManageEmailIndexRoute: appManageEmailIndexRoute,
  appManageMonitorIndexRoute: appManageMonitorIndexRoute,
  appManageMuteIndexRoute: appManageMuteIndexRoute,
  appManageOauthIndexRoute: appManageOauthIndexRoute,
  appManagePermissionIndexRoute: appManagePermissionIndexRoute,
  appManageSfuIndexRoute: appManageSfuIndexRoute,
  appManageStorageIndexRoute: appManageStorageIndexRoute,
  appManageUsersIndexRoute: appManageUsersIndexRoute,
}

const appManageRouteRouteWithChildren = appManageRouteRoute._addFileChildren(
  appManageRouteRouteChildren,
)

interface appRouteRouteChildren {
  appIndexRouteRoute: typeof appIndexRouteRoute
  appManageRouteRoute: typeof appManageRouteRouteWithChildren
  appProfileRouteRoute: typeof appProfileRouteRoute
  appChannelIndexRoute: typeof appChannelIndexRoute
  appChatIndexRoute: typeof appChatIndexRoute
  appDiscoverIndexRoute: typeof appDiscoverIndexRoute
  appIndexIndexRoute: typeof appIndexIndexRoute
  appLinkIndexRoute: typeof appLinkIndexRoute
  appGuildGuildUUIDManageRoute: typeof appGuildGuildUUIDManageRoute
  appGuildGuildUUIDIndexRoute: typeof appGuildGuildUUIDIndexRoute
  appInviteGCodeIndexRoute: typeof appInviteGCodeIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRouteRoute: appIndexRouteRoute,
  appManageRouteRoute: appManageRouteRouteWithChildren,
  appProfileRouteRoute: appProfileRouteRoute,
  appChannelIndexRoute: appChannelIndexRoute,
  appChatIndexRoute: appChatIndexRoute,
  appDiscoverIndexRoute: appDiscoverIndexRoute,
  appIndexIndexRoute: appIndexIndexRoute,
  appLinkIndexRoute: appLinkIndexRoute,
  appGuildGuildUUIDManageRoute: appGuildGuildUUIDManageRoute,
  appGuildGuildUUIDIndexRoute: appGuildGuildUUIDIndexRoute,
  appInviteGCodeIndexRoute: appInviteGCodeIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
